config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  root 'home#index'

  resources :parkings do
    get :parking_info, on: :collection
    post :photo_update, on: :collection
  end

  resources :slots do
    put :change, on: :member
  end
  

  resources :admin
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parkitapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="container">
	<%= link_to "Parkit", home_index_path, id: "logo" %>
        <nav>
	  <% if user_signed_in? %>
	  <li>
	    <!-- <p> Hola <%= current_user.email %> </p> -->
	    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
	  </li>
	  
	  <% else %>
	  <!-- <li> -->
	  <!--   <%= link_to('Login', new_user_session_path) %> -->
	  <!-- </li> -->
	  <% end %>
	  
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Pagina principal",   home_index_path %></li>
            <li><%= link_to "Parqueaderos",   parkings_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
          </ul>
        </nav>
	
      </div>

    </div>
  </header>
  
  <div id="main-container" class="container">
    <div class="row">
      <div class="col-xs-3">
	<h3> Parkit Web</h3>
	<p> Modulo de administracion para la aplicacion parkit </p>
      </div>
      <div class="col-xs-6">
	<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
	<% end %>	
	<%= yield %>
      </div>
    </div>
  </div>    

</body>
</html>